Simulation of task scheduling
cs-24-sw-8-04/scheduling pull request #147
Opened 2024-05-02 11:14 UTC by Darkros1245

We can simulate the scheduling of tasks, and compare the naive and global algorithm with the simulation

2024-05-02 11:56 UTC, S3JER approved these changes

2024-05-07 10:55 UTC, henneboy requested changes
Missing tests?

2024-05-10 12:24 UTC, Puvikaran2001 approved these changes

2024-05-10 12:24 UTC, Puvikaran2001 commented on simulator/src/compare_algorithms.rs
> +}
Er denne function heller ikke defineret i benchmark.rs

2024-05-14 07:13 UTC, merged