Started working on a test suite for testing the current and coming scheduling algorithms
cs-24-sw-8-04/scheduling pull request #62
Opened 2024-04-12 17:52 UTC by Mikkel-Boje

Made macro for creating the expected result and a factory for creating tasks for the tests

2024-04-14 13:10 UTC, Mikkel-Boje commented on backend/src/scheduling/scheduler.rs
> +            .unwrap();
Unwrap, cause the assert above checks this will result in Ok

2024-04-16 07:34 UTC, Darkros1245 requested changes

2024-04-16 07:34 UTC, Darkros1245 commented on backend/src/scheduling/scheduler.rs
> +fn add_event(graph: &DiscreteGraph, task: &Task, timeslot: i32) -> Result<Event> {
```suggestion
fn make_unpublished_event(graph: &DiscreteGraph, task: &Task, timeslot: i32) -> Result<Event> {
```

2024-04-16 07:34 UTC, Darkros1245 commented on backend/src/scheduling/scheduler.rs
> +                })
```suggestion
                });
```

2024-04-16 07:53 UTC, Mikkel-Boje commented on backend/src/scheduling/scheduler.rs
> +fn add_event(graph: &DiscreteGraph, task: &Task, timeslot: i32) -> Result<Event> {
Fixed

2024-04-16 07:53 UTC, Mikkel-Boje commented on backend/src/scheduling/scheduler.rs
> +                })
Whatever :P but fixed

2024-04-16 08:03 UTC, Darkros1245 approved these changes

2024-04-16 08:04 UTC, henneboy approved these changes
Lgtm

2024-04-16 08:49 UTC, merged