The simulation can create arbitrary users, devices, and tasks now
cs-24-sw-8-04/scheduling pull request #71
Opened 2024-04-16 12:10 UTC by Darkros1245

The simulation can create arbitrary users, devices, and tasks now.
This has also been tested 🙃

2024-04-16 12:26 UTC, henneboy commented on simulator/src/main.rs
> +    println!("Auto tokens: {:?}", auth_tokens);
Auth?
```suggestion
    println!("Auth tokens: {:?}", auth_tokens);
```

2024-04-17 08:18 UTC, S3JER approved these changes

2024-04-17 08:22 UTC, Mikkel-Boje requested changes

2024-04-17 08:27 UTC, Mikkel-Boje commented on simulator/src/generate_data.rs
> +            task_onwership.insert(device.clone(), tasks);
```suggestion
            task_ownership.insert(device.clone(), tasks);
```

2024-04-17 08:33 UTC, Mikkel-Boje approved these changes

2024-04-17 08:46 UTC, merged