Connecting front backend login and signup page - stores auth token and username in datastore
cs-24-sw-8-04/scheduling pull request #72
Opened 2024-04-17 08:30 UTC by Puvikaran2001

Connected login and signup page to backend.
Made an account page where the user can logout of the app.
Store the auth token and username in a DataStore, meaning stores the auth token and username, such that when reopening the app, it will show the home page if the user is logged in before closing the app.

2024-04-17 09:01 UTC, S3JER requested changes

2024-04-17 09:24 UTC, Darkros1245 approved these changes

2024-04-17 11:21 UTC, mads256h requested changes
Small stuff

2024-04-17 11:21 UTC, mads256h commented on frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/AccountDataSource.kt
> +            account[key] ?: throw UserNotLoggedIn("The user is not logged in!")
Rename UserNotLoggedIn To UserNotLoggedInException

2024-04-17 11:21 UTC, mads256h commented on frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/AccountDataSource.kt
> +        } catch (e: Throwable) {
This seems a bit overkill to catch all throwables.

2024-04-17 11:21 UTC, mads256h commented on frontend/app/src/main/java/dk/scheduling/schedulingfrontend/datasources/AccountDataSource.kt
> +        } catch (e: Throwable) {
At least pass the exception to UserNotLoggedInException and save it in an inner exception field so we can see what went wrong.

2024-04-17 11:21 UTC, mads256h commented on frontend/app/src/main/java/testdata/DummyAccountRepository.kt
> +        return UUID.randomUUID()
Maybe not return a new random UUID every time we get the auth token. Seems pretty unexpected.

2024-04-18 10:09 UTC, S3JER approved these changes

2024-04-18 10:15 UTC, merged